# Environment
env=qa

qa.url=http://localhost:3000
qa.username=krishnap
qa.password=manager

staging.url=http://staging-url.com
staging.username=admin
staging.password=admin123

# Browser
browser=chromium
headless=false
